version: 2

models:
  - name: staging_orders
    description: "Staging table for Olist Orders Dataset"
    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list:
            - order_id
      - dbt_expectations.expect_column_values_to_be_in_set:
          column_name: order_status
          value_set:
            - delivered
            - shipped
            - canceled
            - invoiced
            - processing
            - approved
            - created