version: 2

sources: 
  - name: brazillian_ecommerce
    database: ecommerce-analytics-475706
    schema: dbt_ecommerce_raw
    tables:
      - name: olist_customer_dataset
      - name: olist_orders_dataset
      - name: olist_order_items_dataset
      - name: olist_products_dataset
      - name: olist_sellers_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_geolocation_dataset
      - name: product_category_name_translation
