version: 2

sources: 
  - name: ecommerce_db
    database: ecommerce-analytics-475706
    schema: dbt_ecommerce_raw
    tables:
      - name: customers
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: order_dataset
      - name: products
      - name: sellers
      - name: product_category_name_translation
      - name: geolocation