dbt_ecommerce_analytics:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_PROJECT') }}"
      threads: 4
      type: bigquery
  target: dev
